spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/360B_user_database
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/360B_user_database
    user: root
    password: 12345
    locations: classpath:db/migration

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

jwt:
  valid-duration: 300
  refreshable-duration: 172800
  signer-key: BWHX28bDtNd9+mWCCZ7gi52UmXIkJJzi5qqdkNZUEghdrQ7Hoal4U1B2CqFc+3uA
