spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/360b_chat_database
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/360b_chat_database
    user: root
    password: 12345
    locations: classpath:db/migration
server:
  port: 9002

gemini:
  api:
    url: ${GEMINI_API_URL}


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
